from enum import StrEnum


class MissionStatus(StrEnum):
    WAITING = "WAITING"
    GOING = "GOING"
    SHOPPING = "SHOPPING"
    RETURNING = "RETURNING"
    COMPLETED = "COMPLETED"


class RouteKind(StrEnum):
    OUTBOUND = "OUTBOUND"
    RETURNING = "RETURNING"


class RouteStepKind(StrEnum):
    UNKNOWN = "UNKNOWN"
    STRAIGHT = "STRAIGHT"
    TURN_LEFT = "TURN_LEFT"
    TURN_RIGHT = "TURN_RIGHT"
    CROSSWALK = "CROSSWALK"
    ARRIVAL = "ARRIVAL"


class ItemVerdict(StrEnum):
    MATCH = "MATCH"
    SIMILAR = "SIMILAR"
    MISMATCH = "MISMATCH"
    UNKNOWN = "UNKNOWN"


class MissionEventType(StrEnum):
    STATUS_CHANGED = "STATUS_CHANGED"
    OFF_ROUTE = "OFF_ROUTE"
    WRONG_WAY = "WRONG_WAY"
    ARRIVED_STORE = "ARRIVED_STORE"
    ROAD_HAZARD = "ROAD_HAZARD"
    VISION_UNAVAILABLE = "VISION_UNAVAILABLE"
    ITEM_VERIFIED = "ITEM_VERIFIED"
    RETURNING = "RETURNING"
    COMPLETED = "COMPLETED"
    LOCATION_STALE = "LOCATION_STALE"


class JoinCodeStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INVALID = "INVALID"
    EXPIRED = "EXPIRED"
    ALREADY_USED = "ALREADY_USED"
